server:
  port: 31000
spring:
  application:
    name: manage-cms-client
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1